# Generated by Django 4.2.1 on 2023-07-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychess', '0002_game_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='roomCode',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
