# Generated by Django 4.2.1 on 2023-07-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pychess', '0003_alter_game_roomcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='piece',
        ),
        migrations.AddField(
            model_name='move',
            name='pieceID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
